apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-app1
  template:
    metadata:
      labels:
        app: weather-app1
    spec:
      containers:
      - name: weather-app1
        image: localhost:5000/weather-app:latest  # Updated image name
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app1-service
spec:
  type: NodePort
  selector:
    app: weather-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
