stages:
  collect:
    cmd: python collect_weather2.py
    outs:
      - data/raw_live_data.csv

  preprocess:
    cmd: python preprocess.py
    deps:
      - data/raw_data.csv
    outs:
      - data/processed_data.csv

  train:
    cmd: python train_model.py
    deps:
      - data/processed_data.csv
    outs:
      - model/model.pkl
